import { numberFromFormValue } from "@/lib/forms/number";

describe("numberFromFormValue", () => {
  it("keeps dot decimals generated by formatted currency inputs", () => {
    expect(numberFromFormValue("700.00")).toBe(700);
    expect(numberFromFormValue("1234.56")).toBe(1234.56);
  });

  it("parses Brazilian display currency values", () => {
    expect(numberFromFormValue("700,00")).toBe(700);
    expect(numberFromFormValue("R$ 1.234,56")).toBe(1234.56);
  });

  it("does not turn cents-safe values into inflated integers", () => {
    expect(numberFromFormValue("70000")).toBe(70000);
    expect(numberFromFormValue("0.70")).toBe(0.7);
  });
});
